import { readFileSync, existsSync, readdirSync } from "node:fs";
import path from "node:path";
import { writeJsonAtomic } from "./atomic";
import { curatedId } from "./uid";
import { parseFlexible, zone } from "./time";
import { masterId } from "./recur";
import {
  EventFileSchema,
  EventInputSchema,
  type DayboardEvent,
  type EventInput,
} from "./schema";

/**
 * Reading and writing `data/layers/*.json` — the calendar's own storage.
 *
 * THIS IS THE ONE BOARD-WRITTEN THING UNDER data/layers/, and the rule it looks
 * like it breaks is worth stating. Everything else the board writes lives at
 * `data/` root, because loadCuratedEvents parses every JSON file under layers/
 * and cache/ as an array of events — so a to-do file there would be read,
 * rejected and logged on every render. These ARE arrays of events. They belong
 * here; nothing else does.
 *
 * The other half of that rule was the module cache in layers.ts, which held
 * these files for the life of the process and would have made every write
 * invisible until a restart. It now covers data/cache/ only. See its docblock.
 *
 * Pure functions plus fs, and NOTHING from `next/*` — scripts/event.ts loads
 * this under plain tsx, so the CLI, the chat skill and the editor all write
 * through one validation and one atomic save. The Next-only half is in
 * event-actions.ts.
 */

const DATA = path.join(process.cwd(), "data");
const LAYERS = path.join(DATA, "layers");

export function layerFile(layer: string): string {
  return path.join(LAYERS, `${layer}.json`);
}

/**
 * The layers the board may write to: the ones with a file of their own.
 *
 * Not every layer qualifies. The teams are snapshots of upstream
 * feeds under data/cache/, rewritten wholesale by the refresh routine — an event
 * added to one would vanish on the next run, so the editor never offers them.
 */
export function writableLayers(): string[] {
  if (!existsSync(LAYERS)) return ["personal"];
  const found = readdirSync(LAYERS)
    .filter((name) => name.endsWith(".json"))
    .map((name) => name.slice(0, -5))
    // Generated by the program, not by hand — data/layers/health.json does not
    // exist and must not be created. See health-events.ts.
    .filter((id) => id !== "health");
  return found.length ? found : ["personal"];
}

/** Read one layer's file. Uncached, for the reason in the docblock above. */
export function loadLayerFile(layer: string): DayboardEvent[] {
  try {
    return EventFileSchema.parse(JSON.parse(readFileSync(layerFile(layer), "utf8")));
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw new Error(`data/layers/${layer}.json is unreadable: ${(err as Error).message.split("\n")[0]}`);
  }
}

/**
 * Sort, validate, write atomically.
 *
 * `scripts/event.ts` has always sorted and validated here; the atomic part is
 * new and is what a second writer costs. A plain writeFileSync is fine while a
 * CLI is the only writer, and stops being fine the moment a render can read the
 * file halfway through a Server Action writing it.
 */
export function saveLayerFile(layer: string, events: DayboardEvent[]): void {
  const sorted = [...events].sort((a, b) => a.start.localeCompare(b.start) || a.id.localeCompare(b.id));
  writeJsonAtomic(layerFile(layer), JSON.stringify(EventFileSchema.parse(sorted), null, 2) + "\n");
}

/* ---------------------------------------------------------------- pure ---- */

export function applyAddEvent(list: DayboardEvent[], event: DayboardEvent): DayboardEvent[] {
  if (list.some((e) => e.id === event.id)) {
    throw new Error(`There is already an event called that on ${event.start.slice(0, 10)}.`);
  }
  return [...list, event];
}

/**
 * Edit in place, keeping the id and bumping `seq`.
 *
 * THE ID NEVER MOVES, even when the title and the date both change. iOS matches
 * events by UID: a new id reaches the phone as a cancellation and a fresh
 * invitation rather than as an edit, and the old one may simply persist. `seq`
 * going up is the signal that says "same event, new details" — which is why it
 * is here and not left to the caller.
 */
export function applyEditEvent(
  list: DayboardEvent[],
  id: string,
  patch: Partial<DayboardEvent>,
  now: string,
): DayboardEvent[] {
  let found = false;
  const next = list.map((event) => {
    if (event.id !== id) return event;
    found = true;
    return { ...event, ...patch, id: event.id, seq: event.seq + 1, updatedAt: now };
  });
  if (!found) throw new Error(`No event with id "${id}".`);
  return next;
}

export function applyRemoveEvent(list: DayboardEvent[], id: string): DayboardEvent[] {
  if (!list.some((e) => e.id === id)) throw new Error(`No event with id "${id}".`);
  return list.filter((event) => event.id !== id);
}

/**
 * A form's answers as a stored event.
 *
 * `parseFlexible` decides all-day from the shape of the value, the same way the
 * CLI has always done it: a bare date is all-day, anything with a time is not.
 * An all-day END is made exclusive here — you pick the last day you mean, and
 * RFC 5545 stores the morning after.
 */
export function buildCuratedEvent(input: EventInput, now: string, id?: string): DayboardEvent {
  const start = parseFlexible(input.start);
  const end = input.end ? parseFlexible(input.end) : null;

  if (end && end.value < start.value) throw new Error("That ends before it starts.");

  return EventFileSchema.element.parse({
    id: id ?? curatedId(input.layer, input.title, start.value.slice(0, 10)),
    layer: input.layer,
    title: input.title.trim(),
    start: start.value,
    end: end?.value,
    allDay: start.allDay,
    tz: zone(),
    location: input.location?.trim() || undefined,
    url: input.url?.trim() || undefined,
    notes: input.notes?.trim() || undefined,
    source: { kind: "curated" },
    status: input.status,
    recurrence: input.recurrence,
    seq: 0,
    updatedAt: now,
  });
}

/** Which stored event an id refers to, instance or not. */
export function resolveMaster(id: string): string {
  return masterId(id);
}

export { EventInputSchema };
